const { Client } = require("pg");
const postgresql = require("../config/dbConfig");

const getUsers = async (req, res) => {
  const data = [
    {
      title: "Depth first Search",
      author: "Ramprosad Gharami",
      topic: "Graph theory",
      status: "Published",
      date: "3-27-2023 4:10 PM",
      publish_date: "3-27-2023 4:10 PM",
    },
    {
      title: "Depth first Search",
      author: "Ramprosad Gharami",
      topic: "Graph theory",
      status: "Published",
      date: "3-27-2023 4:10 PM",
      publish_date: "3-27-2023 4:10 PM",
    },
    {
      title: "Depth first Search",
      author: "Ramprosad Gharami",
      topic: "Graph theory",
      status: "Published",
      date: "3-27-2023 4:10 PM",
      publish_date: "3-27-2023 4:10 PM",
    },
    {
      title: "Depth first Search",
      author: "Ramprosad Gharami",
      topic: "Graph theory",
      status: "Published",
      date: "3-27-2023 4:10 PM",
      publish_date: "3-27-2023 4:10 PM",
    },
    {
      title: "Depth first Search",
      author: "Ramprosad Gharami",
      topic: "Graph theory",
      status: "Published",
      date: "3-27-2023 4:10 PM",
      publish_date: "3-27-2023 4:10 PM",
    },
    {
      title: "Depth first Search",
      author: "Ramprosad Gharami",
      topic: "Graph theory",
      status: "Published",
      date: "3-27-2023 4:10 PM",
      publish_date: "3-27-2023 4:10 PM",
    },
    {
      title: "Depth first Search",
      author: "Ramprosad Gharami",
      topic: "Graph theory",
      status: "Published",
      date: "3-27-2023 4:10 PM",
      publish_date: "3-27-2023 4:10 PM",
    },
    {
      title: "Depth first Search",
      author: "Ramprosad Gharami",
      topic: "Graph theory",
      status: "Published",
      date: "3-27-2023 4:10 PM",
      publish_date: "3-27-2023 4:10 PM",
    },
    {
      title: "Depth first Search",
      author: "Ramprosad Gharami",
      topic: "Graph theory",
      status: "Published",
      date: "3-27-2023 4:10 PM",
      publish_date: "3-27-2023 4:10 PM",
    },
    {
      title: "Depth first Search",
      author: "Ramprosad Gharami",
      topic: "Graph theory",
      status: "Published",
      date: "3-27-2023 4:10 PM",
      publish_date: "3-27-2023 4:10 PM",
    },
    {
      title: "Depth first Search",
      author: "Ramprosad Gharami",
      topic: "Graph theory",
      status: "Published",
      date: "3-27-2023 4:10 PM",
      publish_date: "3-27-2023 4:10 PM",
    },
    {
      title: "Depth first Search",
      author: "Ramprosad Gharami",
      topic: "Graph theory",
      status: "Published",
      date: "3-27-2023 4:10 PM",
      publish_date: "3-27-2023 4:10 PM",
    },
    {
      title: "Depth first Search",
      author: "Ramprosad Gharami",
      topic: "Graph theory",
      status: "Published",
      date: "3-27-2023 4:10 PM",
      publish_date: "3-27-2023 4:10 PM",
    },
    {
      title: "Depth first Search",
      author: "Ramprosad Gharami",
      topic: "Graph theory",
      status: "Published",
      date: "3-27-2023 4:10 PM",
      publish_date: "3-27-2023 4:10 PM",
    },
    {
      title: "Depth first Search",
      author: "Ramprosad Gharami",
      topic: "Graph theory",
      status: "Published",
      date: "3-27-2023 4:10 PM",
      publish_date: "3-27-2023 4:10 PM",
    },
    {
      title: "Depth first Search",
      author: "Ramprosad Gharami",
      topic: "Graph theory",
      status: "Published",
      date: "3-27-2023 4:10 PM",
      publish_date: "3-27-2023 4:10 PM",
    },
    {
      title: "Depth first Search",
      author: "Ramprosad Gharami",
      topic: "Graph theory",
      status: "Published",
      date: "3-27-2023 4:10 PM",
      publish_date: "3-27-2023 4:10 PM",
    },
  ];
  res.status(200).json(data);
};

module.exports = getUsers;
