require("dotenv").config();

const {
  SERVER_PORT,
  HOST,
  DATABASE,
  USER_NAME,
  PASSWORD,
  DATABASE_PORT,
  SMTP_USERNAME,
  SMTP_PASSWORD,
  SMTP_SECRET_KEY,
  USER_SECRET_KEY,
  ADMIN_SECRET_KEY,
} = process.env;

const ENV = {
  SERVER_PORT: SERVER_PORT,
  HOST: HOST,
  DATABASE: DATABASE,
  USER_NAME: USER_NAME,
  PASSWORD: PASSWORD,
  DATABASE_PORT: DATABASE_PORT,
  SMTP_USERNAME: SMTP_USERNAME,
  SMTP_PASSWORD: SMTP_PASSWORD,
  SMTP_SECRET_KEY: SMTP_SECRET_KEY,
  USER_SECRET_KEY: USER_SECRET_KEY,
  ADMIN_SECRET_KEY: ADMIN_SECRET_KEY,
};

module.exports = ENV;
